### PR TITLE
Feature/nibblepeg with switch

### PR DESCRIPTION
**Pull request by misamura**
I created a new manual for a "Nibble Peg with an on/off switch".

+ I copied the original "NibblePegDIP" manual, extended it with the additional steps and images for the on/off switch, and I created the DE and EN manual PDFs using latex.
+ I extended the base README to include a section with the new Nibble PEG with on/off switch manual.

### CODE REVIEW

**Comment by misamura** [comment]
Oh, and I changed the author/idea/descriptions fields so that it includes Christopher's and my name (Hannes)

**Comment by misamura** [comment]
Unfortunately, my Mac git changed some of the base files due to encoding/end Of Line symbols, so that the complete file appears on diff..

**Comment by marove2000** [comment]
Hi Hannes,

thank you for your contribution. I've merged your pull request. Thank you for making this Soldering Tutorial even better :).

**Comment by marove2000** [comment]
Hey Hannes,

I've found a minor bug. It seems the picutre 01-DSC06774.JPG is missing. Can you upload it? Then I can change back the README.md

Regards

**Comment by misamura** [comment]
Hi Timo, thanks for merging.

You are correct about the picture. I will create a new pull request!

**Comment by marove2000** [comment]
Merged everything. Thanks again for your contribution :)

**Comment by misamura** [comment]
Thanks for letting me participate :)

**Pull request merged**
