### PR TITLE
Esperanto translation

### PR DESCRIPTION
**Pull request by jxetkubo**
Manual language files translated form German to Esperanto.
Lingvaj dosieroj de la instruado elgermaniĝis.

### CODE REVIEW

**Comment by rralf** [comment]
Can someone review this? :-)

**Comment by jxetkubo** [comment]
On 26.12.19 15:09, Ralf Ramsauer wrote:
> Can someone review this? :-)

Ask at the Esperanto Assembly!



Merry Xmas!

wuerfel

**Comment by rralf** [comment]
Is this still relevant or can we close this? I think the project would benefit from an esperanto translation, but someone would have to maintain it.

**Comment by ventilator** [comment]
I would say, we keep the translations but mark the Esperanto release as experimental and see if someone uses it

**Comment by rralf** [comment]
Well, the branch won't merge without conflicts, and there's probably no one to resolve the conflicts. Neither can we review the changes. I'd say we can close this one for the moment, and and point to this branch, if someone wants to contribute an esperanto translation.

**Comment by marove2000** [comment]
Hi everyone,

due to a config-change and the lack of Esperanto speaking people in the dev-team I have to close this Pull Request.
Unfortunately I had to do the same with the french translation due to the config-change.

We are happy about any other language, but we are dependent on the translators in a event of a change in the manuals or config change. I would love to see an updated version which adds other languages with the new config.

Hint: The older sets are matured enough that no manual change or typo is needed to be fixed. I would start with them :).

**Pull request closed without merging**
